spring:
  datasource:
    url: jdbc:mysql://somacode:3306/somacodedb
    username: root
    password: 1234
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true

server:
  port: 8080

custom:
  username: admin@somacode.com
  password: 1234
  version: 1.0
  email-enabled: true
  my-secret-token: my-secret-token
  access-token-validity: 50000
  refresh-token-validity: 50000
  base-url: api.somacode.com
  protocol: https